services:
  task-pred:
    build: .
    container_name: task_prediction
    user: 1000:1000
    network_mode: host

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ~/data/:/app/data/
    
    environment:
      - TASK_PRED__DATA_DIR=/app/data
      - TASK_PRED__NATS_HOST=nats://127.0.0.1:4222
      - TASK_PRED__SAMPLING_INTERVAL_MS=2000

      # Model
      - TASK_PRED__MODEL__MODEL_DIR=/app/model
      - TASK_PRED__MODEL__FORCE_STAGE_B=true
      - TASK_PRED__MODEL__ALWAYS_VALIDATE_INPUT=true
      
      # Parquet sink
      - TASK_PRED__PARQUET__ENABLED=true
      - TASK_PRED__PARQUET__QUEUE_SIZE=50
      - TASK_PRED__PARQUET__MAX_BUFFER_SIZE=5

      # Terminal sink
      - TASK_PRED__TERMINAL__ENABLED=true

      # NATS sink (protobuf messages)
      - TASK_PRED__NATS__ENABLED=true
      - TASK_PRED__NATS__SUBJECT=intent.task_prediction
      
      # Logging
      - TASK_PRED__LOGGING__LEVEL=DEBUG
    
      # Fix Matplotlib warning by pointing to a writable location
      - MPLCONFIGDIR=/tmp/matplotlib