services:
  task-pred:
    build: .
    container_name: task_prediction

    network_mode: host
    user: 1000:1000
    
    environment:
      - TASK_PRED__NATS_HOST=nats://localhost:4222
      - TASK_PRED__SAMPLING_INTERVAL_MS=2000

      # Model
      - TASK_PRED__MODEL__MODEL_DIR=/app/model
      - TASK_PRED__MODEL__FORCE_STAGE_B=true
      - TASK_PRED__MODEL__ALWAYS_VALIDATE_INPUT=true
      
      # Parquet sink
      - TASK_PRED__PARQUET__ENABLED=true
      - TASK_PRED__PARQUET__OUTPUT_DIR=/app/data

      # Terminal sink
      - TASK_PRED__TERMINAL__ENABLED=true

      # NATS sink (protobuf messages)
      - TASK_PRED__NATS__ENABLED=true
      - TASK_PRED__NATS__SUBJECT=intent.task_prediction
      
      # Logging
      - TASK_PRED__LOGGING__LEVEL=DEBUG
    
      # Fix Matplotlib warning by pointing to a writable location
      - MPLCONFIGDIR=/tmp/matplotlib
    volumes:
      # Mounts local ./data folder to the container's data folder
      - ./data:/app/data
    
    # Required for host.docker.internal to work on Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    restart: unless-stopped

volumes:
  data: